### ISSUE TITLE
Running the bot

### ISSUE THREAD

**Issue by guilhermepiccioni** [zonkia/6SFX#1]
Good morning

I really liked the code and the way it shows the results in the terminal. I would like to know if I have to do something different for the bot to open orders? I made the clone of your repository and in my case it only shows the message "Brak possibleTradesWithAllOk aby otworzyć hedge". The bot runs but does not perform any order.

Would you help me ?

**Comment by zonkia** [comment]
Hedging is part of the algorithm that works only if two conditions are met:
1. There is at least one position already opened
2. possibleTradesWithAllOk dictionary is not empty

My guess is that technical analysis didn't allow any trade to be opened at the time of your testing (thus possibleTradesWithAllOk dictionary is empty)

Also please note that bot was designed for polish currency (PLN). 
For example: if you have EUR account and trade EURUSD, you should force variable: **currencyExchangePLN = {tradedPair: 1}**
If you don't change currencyExchangePLN to match your account currency, the opened positions will be much smaller or much bigger than they should. 
For example: if you have EUR account and trade EURUSD, the positions will be aprox. 5x smaller than they should be.

**Comment by guilhermepiccioni** [comment]
Got it, I managed to find the variable you commented on. Should I change the API that the value is being collected or would it be another change I need to make?

Sorry for these questions, I'm new as a programmer and some things are new to me. If you don't mind, I would really appreciate it if you could help me get it running on my machine. I am looking to trade precisely this EURUSD currency.

**Comment by zonkia** [comment]
If you want to trade EURUSD and your account is in EUR, you can leave it like this: **currencyExchangePLN = {tradedPair: 1}**
Changing API to collect currency exchange rates is not necessary in this case.
